# Generated by Django 4.2 on 2023-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraud',
            name='transaction_id',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
